name: Autograding Tests
'on':
 - push
 - repository_dispatch
permissions:
 checks: write
 actions: read
 contents: read
jobs:
 run-autograding-tests:
   runs-on: ubuntu-latest
   if: github.actor != 'github-classroom[bot]'
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: Install dependencies
       run: |
         pip install pytest
         pip install numpy
         pip install pandas
         pip install matplotlib

     - name: NumPy Exercise 1 Test
       id: numpy_01
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 01numpy01
         command: pytest -vk "test_01numpy01"
         timeout: 20
         max-score: 1

     - name: NumPy Exercise 2 Test
       id: numpy_02 
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 01numpy02
         command: pytest -vk "test_01numpy02"
         timeout: 20
         max-score: 1

     - name: NumPy Exercise 3 Test
       id: numpy_03
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 01numpy03
         command: pytest -vk "test_01numpy03"
         timeout: 20
         max-score: 1

     - name: Pandas Exercise 1 Test
       id: pandas_01
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 02pandas01
         command: pytest -vk "test_02pandas01"
         timeout: 20
         max-score: 1

     - name: Pandas Exercise 2 Test
       id: pandas_02
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 02pandas02
         command: pytest -vk "test_02pandas02"
         timeout: 20
         max-score: 1

     - name: Pandas Exercise 3 Test
       id: pandas_03
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 02pandas03
         command: pytest -vk "test_02pandas03"
         timeout: 20
         max-score: 1

     - name: Pandas Exercise 4 Test
       id: pandas_04
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 02pandas04
         command: pytest -vk "test_02pandas04"
         timeout: 20
         max-score: 1

     - name: Pandas Exercise 5 Test
       id: pandas_05
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 02pandas05
         command: pytest -vk "test_02pandas05"
         timeout: 20
         max-score: 1

     - name: Matplotlib Exercise 1 Test
       id: matplotlib_01
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 03matplotlib01
         command: pytest -vk "test_03matplotlib01"
         timeout: 20
         max-score: 1

     - name: Matplotlib Exercise 2 Test
       id: matplotlib_02
       uses: classroom-resources/autograding-command-grader@v1
       with:
         test-name: 03matplotlib02
         command: pytest -vk "test_03matplotlib02"
         timeout: 20
         max-score: 1

     - name: Autograding Reporter
       uses: classroom-resources/autograding-grading-reporter@v1
       env:
         NUMPY_01_RESULTS: "${{steps.numpy_01.outputs.result}}"
         NUMPY_02_RESULTS: "${{steps.numpy_02.outputs.result}}"
         NUMPY_03_RESULTS: "${{steps.numpy_03.outputs.result}}"
         PANDAS_01_RESULTS: "${{steps.pandas_01.outputs.result}}"
         PANDAS_02_RESULTS: "${{steps.pandas_02.outputs.result}}"
         PANDAS_03_RESULTS: "${{steps.pandas_03.outputs.result}}"
         PANDAS_04_RESULTS: "${{steps.pandas_04.outputs.result}}"
         PANDAS_05_RESULTS: "${{steps.pandas_05.outputs.result}}"
         MATPLOTLIB_01_RESULTS: "${{steps.matplotlib_01.outputs.result}}"
         MATPLOTLIB_02_RESULTS: "${{steps.matplotlib_02.outputs.result}}"
       with:
         runners: numpy_01,numpy_02,numpy_03,pandas_01,pandas_02,pandas_03,pandas_04,pandas_05,matplotlib_01,matplotlib_02